name: 'e2e'
description: 'Прогон e2e тестов'
inputs:
  node-version:
    required: true
    default: '18'
runs:
  using: "composite"
  steps:
    - name: Установка зависимостей
      run: npm ci
      shell: bash
    - name: Установка playwright
      run: npx playwright install
      shell: bash
    - name: Прогон тестов
      run: npm run e2e-ci
      shell: bash
