name: Деплой на github pages

on:
  push:
    branches:
      - master

jobs:
  deploy_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Чекаут
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Установа зависимостей
        run: npm ci
      - name: Сборка
        run: PUBLIC_URL="/shri-unit-demo-cra" npm run build
      - name: Деплоймент
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build